-- Boletines: newsletters generated by Nexión and published to Slack.
-- Migrated from n8n workflow "IA news day" (data tables ia_news_sources + boletines_historial).
-- Newsletters are organization-level (one Slack channel for the whole team), not workspace-scoped.

create table if not exists public.newsletters (
  id text primary key,
  name text not null,
  description text,
  slack_channel_id text not null,
  schedule_label text not null,
  model text not null,
  is_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.newsletter_sources (
  id uuid primary key default gen_random_uuid(),
  newsletter_id text not null references public.newsletters(id) on delete cascade,
  source_key text not null,
  name text not null,
  url text not null,
  source_type text not null default 'RSS' check (source_type in ('RSS', 'HTML', 'SITEMAP', 'REDDIT')),
  category text not null default 'media',
  priority text not null default 'medium' check (priority in ('high', 'medium', 'low')),
  max_items integer not null default 3 check (max_items between 1 and 20),
  is_active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (newsletter_id, source_key)
);

create table if not exists public.newsletter_editions (
  id uuid primary key default gen_random_uuid(),
  newsletter_id text not null references public.newsletters(id) on delete cascade,
  status text not null check (status in ('published', 'preview', 'skipped', 'failed')),
  trigger text not null check (trigger in ('cron', 'manual')),
  message text,
  pills jsonb not null default '[]'::jsonb,
  stats jsonb not null default '{}'::jsonb,
  error text,
  model text,
  usage jsonb,
  slack_ts text,
  created_at timestamptz not null default now()
);

create index if not exists idx_newsletter_editions_recent
  on public.newsletter_editions (newsletter_id, created_at desc);

-- URLs already published, so a newsletter never repeats a story.
create table if not exists public.newsletter_seen_items (
  id uuid primary key default gen_random_uuid(),
  newsletter_id text not null references public.newsletters(id) on delete cascade,
  url text not null,
  title text,
  edition_id uuid references public.newsletter_editions(id) on delete set null,
  seen_at timestamptz not null default now(),
  unique (newsletter_id, url)
);

alter table public.newsletters enable row level security;
alter table public.newsletter_sources enable row level security;
alter table public.newsletter_editions enable row level security;
alter table public.newsletter_seen_items enable row level security;

-- Any signed-in team member can read; the pipeline writes with the service role.
create policy "authenticated_can_read_newsletters"
  on public.newsletters for select to authenticated using (true);

create policy "authenticated_can_update_newsletters"
  on public.newsletters for update to authenticated using (true) with check (true);

create policy "authenticated_can_read_newsletter_sources"
  on public.newsletter_sources for select to authenticated using (true);

create policy "authenticated_can_update_newsletter_sources"
  on public.newsletter_sources for update to authenticated using (true) with check (true);

create policy "authenticated_can_read_newsletter_editions"
  on public.newsletter_editions for select to authenticated using (true);

create policy "authenticated_can_read_newsletter_seen_items"
  on public.newsletter_seen_items for select to authenticated using (true);

-- The UI may only flip the on/off switches; channel, URLs and model stay service-role only.
revoke update on public.newsletters from authenticated, anon;
grant update (is_enabled, updated_at) on public.newsletters to authenticated;
revoke update on public.newsletter_sources from authenticated, anon;
grant update (is_active, updated_at) on public.newsletter_sources to authenticated;

-- ---------------------------------------------------------------------------
-- Seed: IA News Day
-- ---------------------------------------------------------------------------

insert into public.newsletters (id, name, description, slack_channel_id, schedule_label, model)
values (
  'ia-news-day',
  'IA News Day',
  '2 pills diarias con las noticias de IA más útiles para Producto, UX, Automatización y Negocio.',
  'C0A34HW4HGR',
  'Lunes a viernes · 8:00 a. m. (Bogotá)',
  'claude-haiku-4-5-20251001'
)
on conflict (id) do nothing;

insert into public.newsletter_sources
  (newsletter_id, source_key, name, url, source_type, category, priority, max_items, is_active, notes)
values
  ('ia-news-day', 'openai_news', 'OpenAI News', 'https://openai.com/news/rss.xml', 'RSS', 'official', 'high', 5, true, 'Fuente oficial de OpenAI para announcements, producto, modelos y research.'),
  ('ia-news-day', 'openai_sitemap', 'OpenAI Sitemap', 'https://openai.com/sitemap.xml', 'SITEMAP', 'official', 'medium', 5, true, 'Fallback para detectar páginas recientes de OpenAI cuando RSS no responda.'),
  ('ia-news-day', 'anthropic_news', 'Anthropic News', 'https://www.anthropic.com/news/rss.xml', 'RSS', 'official', 'high', 5, true, 'Fuente oficial de Anthropic para Claude, announcements, safety y enterprise.'),
  ('ia-news-day', 'anthropic_research', 'Anthropic Research', 'https://www.anthropic.com/research', 'HTML', 'research', 'medium', 4, true, 'Research y alineación de Anthropic.'),
  ('ia-news-day', 'google_ai_blog', 'Google AI Blog', 'https://blog.google/technology/ai/rss/', 'RSS', 'official', 'high', 5, true, 'Fuente oficial de Google AI.'),
  ('ia-news-day', 'google_deepmind_blog', 'Google DeepMind Blog', 'https://deepmind.google/blog/rss.xml', 'RSS', 'research', 'high', 5, true, 'Modelos, research y avances de DeepMind.'),
  ('ia-news-day', 'microsoft_ai_blog', 'Microsoft AI Blog', 'https://blogs.microsoft.com/ai/feed/', 'RSS', 'official', 'medium', 4, true, 'Announcements, Copilot, enterprise AI y partnerships de Microsoft.'),
  ('ia-news-day', 'microsoft_research_ai', 'Microsoft Research AI', 'https://www.microsoft.com/en-us/research/feed/?facet%5Btax%5D%5Bmsr-research-area%5D%5B%5D=13556', 'RSS', 'research', 'low', 3, false, 'Research técnico; activar solo si el feed funciona y no genera ruido.'),
  ('ia-news-day', 'meta_ai_blog', 'Meta AI Blog', 'https://ai.meta.com/blog/rss/', 'RSS', 'official', 'medium', 4, true, 'Modelos abiertos, Llama, research y herramientas Meta AI.'),
  ('ia-news-day', 'nvidia_ai_blog', 'NVIDIA AI Blog', 'https://blogs.nvidia.com/blog/category/deep-learning/feed/', 'RSS', 'official', 'medium', 4, true, 'Infraestructura, GPUs, enterprise AI y modelos.'),
  ('ia-news-day', 'mistral_news', 'Mistral AI News', 'https://mistral.ai/news/rss.xml', 'RSS', 'official', 'medium', 4, true, 'Modelos, producto y announcements de Mistral.'),
  ('ia-news-day', 'stability_ai_news', 'Stability AI News', 'https://stability.ai/news/rss.xml', 'RSS', 'official', 'low', 3, false, 'Generación multimodal; activar si la URL responde.'),
  ('ia-news-day', 'techcrunch_ai', 'TechCrunch AI', 'https://techcrunch.com/tag/artificial-intelligence/feed/', 'RSS', 'media', 'high', 5, true, 'Startups, negocio, lanzamientos y mercado IA.'),
  ('ia-news-day', 'the_decoder', 'The Decoder', 'https://the-decoder.com/feed/', 'RSS', 'media', 'high', 5, true, 'Noticias de IA, producto, herramientas, modelos y aplicaciones.'),
  ('ia-news-day', 'tldr_ai', 'TLDR AI', 'https://tldr.tech/api/rss/ai', 'RSS', 'media', 'medium', 2, true, 'Radar diario; limitar porque cada item mezcla varias noticias.'),
  ('ia-news-day', 'venturebeat_ai', 'VentureBeat AI', 'https://venturebeat.com/category/ai/feed/', 'RSS', 'media', 'medium', 4, true, 'Enterprise AI, herramientas, negocio y automatización.'),
  ('ia-news-day', 'mit_tech_review_ai', 'MIT Technology Review AI', 'https://www.technologyreview.com/topic/artificial-intelligence/feed/', 'RSS', 'media', 'medium', 4, true, 'Tendencias, riesgos, investigación aplicada y regulación.'),
  ('ia-news-day', 'theverge_ai', 'The Verge AI', 'https://www.theverge.com/ai-artificial-intelligence/rss/index.xml', 'RSS', 'media', 'medium', 3, true, 'Producto, herramientas IA y consumo.'),
  ('ia-news-day', 'ars_technica_techlab', 'Ars Technica Technology Lab', 'https://feeds.arstechnica.com/arstechnica/technology-lab', 'RSS', 'media', 'low', 3, true, 'Técnico/industria; requiere filtro IA fuerte.'),
  ('ia-news-day', 'wired_ai', 'WIRED AI', 'https://www.wired.com/feed/tag/ai/latest/rss', 'RSS', 'media', 'medium', 3, true, 'IA, sociedad, producto y riesgos.'),
  ('ia-news-day', 'the_information_ai', 'The Information AI', 'https://www.theinformation.com/feed', 'RSS', 'media', 'low', 2, false, 'Puede requerir paywall; activar solo si entrega metadata útil.'),
  ('ia-news-day', 'axios_ai', 'Axios AI', 'https://www.axios.com/technology/artificial-intelligence/rss.xml', 'RSS', 'media', 'medium', 3, true, 'Señales de negocio, política, mercado y adopción IA.'),
  ('ia-news-day', 'semianalysis', 'SemiAnalysis', 'https://semianalysis.com/feed/', 'RSS', 'research', 'low', 2, false, 'Infraestructura, chips y economía de IA; denso.'),
  ('ia-news-day', 'mit_news_ai', 'MIT News AI', 'https://news.mit.edu/rss/topic/artificial-intelligence2', 'RSS', 'research', 'medium', 4, true, 'Research aplicado y noticias académicas de IA.'),
  ('ia-news-day', 'stanford_hai', 'Stanford HAI', 'https://hai.stanford.edu/news/rss.xml', 'RSS', 'research', 'medium', 3, true, 'IA responsable, research, policy y sociedad.'),
  ('ia-news-day', 'berkeley_ai_research', 'Berkeley AI Research', 'https://bair.berkeley.edu/blog/feed.xml', 'RSS', 'research', 'low', 3, false, 'Research técnico; activar si quieres señales más profundas.'),
  ('ia-news-day', 'arxiv_ai', 'arXiv AI', 'https://export.arxiv.org/rss/cs.AI', 'RSS', 'research', 'low', 2, false, 'Muy técnico y ruidoso; usar solo con filtros fuertes.'),
  ('ia-news-day', 'arxiv_cl', 'arXiv Computation and Language', 'https://export.arxiv.org/rss/cs.CL', 'RSS', 'research', 'low', 2, false, 'LLMs/NLP; muy técnico y ruidoso.'),
  ('ia-news-day', 'papers_with_code', 'Papers with Code', 'https://paperswithcode.com/feeds/latest.xml', 'RSS', 'research', 'low', 2, false, 'Modelos y papers; activar si hay filtro técnico sólido.'),
  ('ia-news-day', 'latent_space', 'Latent Space', 'https://www.latent.space/feed', 'RSS', 'dev_tools', 'medium', 3, true, 'Dev tools, agentes, análisis técnico y comunidad builder.'),
  ('ia-news-day', 'simon_willison', 'Simon Willison', 'https://simonwillison.net/atom/everything/', 'RSS', 'dev_tools', 'medium', 3, true, 'LLMs, prompts, agents, tooling y notas prácticas de ingeniería.'),
  ('ia-news-day', 'hugging_face_blog', 'Hugging Face Blog', 'https://huggingface.co/blog/feed.xml', 'RSS', 'dev_tools', 'medium', 3, true, 'Modelos open source, tools, datasets y prácticas IA.'),
  ('ia-news-day', 'replicate_blog', 'Replicate Blog', 'https://replicate.com/blog/rss', 'RSS', 'dev_tools', 'low', 2, false, 'Modelos y demos; activar si aporta herramientas concretas.'),
  ('ia-news-day', 'modal_blog', 'Modal Blog', 'https://modal.com/blog/rss.xml', 'RSS', 'dev_tools', 'low', 2, false, 'Infraestructura IA y despliegue; más técnico.'),
  ('ia-news-day', 'langchain_blog', 'LangChain Blog', 'https://blog.langchain.com/rss/', 'RSS', 'dev_tools', 'medium', 3, true, 'Agentes, RAG, orchestration y aplicaciones LLM.'),
  ('ia-news-day', 'llamaindex_blog', 'LlamaIndex Blog', 'https://www.llamaindex.ai/blog/rss.xml', 'RSS', 'dev_tools', 'medium', 3, true, 'RAG, agentes, data workflows y aplicaciones LLM.'),
  ('ia-news-day', 'anthropic_engineering', 'Anthropic Engineering', 'https://www.anthropic.com/engineering', 'HTML', 'dev_tools', 'medium', 3, true, 'Engineering posts de Anthropic.'),
  ('ia-news-day', 'xataka_ai', 'Xataka IA', 'https://www.xataka.com/tag/inteligencia-artificial/rss2.xml', 'RSS', 'spanish', 'medium', 3, true, 'Fuente en español para aterrizar noticias de IA al equipo.'),
  ('ia-news-day', 'genbeta_ai', 'Genbeta IA', 'https://www.genbeta.com/tag/inteligencia-artificial/rss2.xml', 'RSS', 'spanish', 'low', 2, true, 'Herramientas y consumo IA en español. Usar con filtro de calidad.'),
  ('ia-news-day', 'hipertextual_ai', 'Hipertextual IA', 'https://hipertextual.com/tag/inteligencia-artificial/feed', 'RSS', 'spanish', 'low', 2, false, 'Fuente en español; activar si el feed responde y no mete ruido.'),
  ('ia-news-day', 'reddit_artificial', 'Reddit r/artificial', 'https://www.reddit.com/r/artificial/.rss', 'REDDIT', 'community', 'low', 1, false, 'Ruidoso; dejar desactivado salvo experimentos.'),
  ('ia-news-day', 'reddit_localllama', 'Reddit r/LocalLLaMA', 'https://www.reddit.com/r/LocalLLaMA/.rss', 'REDDIT', 'community', 'low', 1, false, 'Señales open source; ruidoso y técnico.'),
  ('ia-news-day', 'hackernews_ai_search', 'Hacker News AI search', 'https://hnrss.org/newest?q=AI', 'RSS', 'community', 'low', 1, false, 'Muy ruidoso; activar solo si quieres radar temprano.')
on conflict (newsletter_id, source_key) do nothing;

-- History imported from n8n boletines_historial (tipo_boletin = 'IA').
insert into public.newsletter_seen_items (newsletter_id, url, title, seen_at)
values
  ('ia-news-day', 'https://deepmind.google/blog/investing-in-multi-agent-ai-safety-research', 'Investing in multi-agent AI safety research', '2026-06-12T13:00:44Z'),
  ('ia-news-day', 'https://openai.com/index/bbva', 'BBVA puts AI at the core of banking with OpenAI', '2026-06-12T13:00:44Z'),
  ('ia-news-day', 'https://openai.com/index/openai-to-acquire-ona', 'OpenAI to acquire Ona', '2026-06-12T13:27:56Z'),
  ('ia-news-day', 'https://techcrunch.com/2026/01/13/ai-drug-discovery-startup-converge-bio-pulls-in-25m-from-bessemer-and-execs-from-meta-openai-and-wiz', 'Converge Bio raises $25M, backed by Bessemer and execs from Meta, OpenAI, Wiz', '2026-06-12T13:27:56Z'),
  ('ia-news-day', 'https://deepmind.google/blog/securing-the-future-of-ai-agents', 'Securing the future of AI agents', '2026-06-19T13:00:46Z'),
  ('ia-news-day', 'https://openai.com/index/chatgpt-enterprise-spend-controls', 'New usage analytics and updated spend controls for enterprises', '2026-06-19T13:00:46Z'),
  ('ia-news-day', 'https://openai.com/index/mapping-ai-jobs-transition-eu', 'Mapping Europe’s AI Workforce Opportunity', '2026-07-03T13:00:41Z'),
  ('ia-news-day', 'https://deepmind.google/blog/introducing-computer-use-in-gemini-3-5-flash', 'Introducing computer use in Gemini 3.5 Flash', '2026-07-03T13:00:41Z'),
  ('ia-news-day', 'https://blog.google/innovation-and-ai/technology/developers-tools/expanding-managed-agents-gemini-api', 'Expanding Managed Agents in Gemini API: background tasks, remote MCP and more', '2026-07-10T13:00:46Z'),
  ('ia-news-day', 'https://openai.com/index/chatgpt-for-your-most-ambitious-work', 'ChatGPT is now a partner for your most ambitious work', '2026-07-10T13:00:46Z'),
  ('ia-news-day', 'https://openai.com/index/managing-ai-investments-in-agentic-era', 'How to manage AI investments in the agentic era', '2026-07-17T13:00:47Z'),
  ('ia-news-day', 'https://deepmind.google/blog/empowering-indias-next-generation-of-innovators-with-atl-saathi', 'Empowering India’s next generation of innovators with ATL Saathi', '2026-07-17T13:00:47Z'),
  ('ia-news-day', 'https://openai.com/index/introducing-openai-presence', 'Introducing OpenAI Presence', '2026-07-24T13:00:44Z'),
  ('ia-news-day', 'https://deepmind.google/blog/introducing-gemini-36-flash-35-flash-lite-and-35-flash-cyber', 'Introducing Gemini 3.6 Flash, 3.5 Flash-Lite, and 3.5 Flash Cyber', '2026-07-24T13:00:44Z'),
  ('ia-news-day', 'https://blog.google/innovation-and-ai/technology/developers-tools/expanding-managed-agents-gemini-api-3-6-flash-hooks', 'Gemini API Managed Agents: 3.6 Flash, hooks, and more', '2026-08-07T13:00:40Z'),
  ('ia-news-day', 'https://deepmind.google/blog/weathernext-ai-model-achieves-breakthrough-in-forecasting-cyclones', 'WeatherNext: AI model achieves breakthrough in forecasting cyclones', '2026-08-07T13:00:40Z'),
  ('ia-news-day', 'https://deepmind.google/blog/putting-sign-language-ai-into-users-hands', 'Putting sign language AI into users’ hands', '2026-08-14T13:00:40Z'),
  ('ia-news-day', 'https://openai.com/index/how-enterprises-put-ai-to-work', 'From assistance to execution: How enterprises put AI to work', '2026-08-14T13:00:40Z'),
  ('ia-news-day', 'https://openai.com/index/legora-financial-statement-review-with-astra', 'Legora reviewed 41 documents in minutes with GPT-6 Astra', '2026-09-04T13:00:39Z'),
  ('ia-news-day', 'https://deepmind.google/blog/introducing-weathernext-3-our-most-advanced-and-accurate-global-weather-ai-model', 'Introducing WeatherNext 3, our most advanced and accurate global weather AI model', '2026-09-04T13:00:39Z'),
  ('ia-news-day', 'https://deepmind.google/blog/introducing-gemini-3-8-flash-and-38-flash-cyber', 'Introducing Gemini 3.8 Flash and 3.8 Flash Cyber', '2026-09-11T13:00:41Z'),
  ('ia-news-day', 'https://blog.google/innovation-and-ai/technology/safety-security/fairwind-program', 'Proactive cyber defense for governments and enterprises', '2026-09-11T13:00:41Z'),
  ('ia-news-day', 'https://openai.com/index/reimagining-advertising-with-ai', 'Reimagining advertising with AI', '2026-09-18T13:00:43Z'),
  ('ia-news-day', 'https://deepmind.google/blog/introducing-gemini-3-8-live-and-3-8-live-extended-thinking', 'Introducing Gemini 3.8 Live and 3.8 Live Extended Thinking', '2026-09-18T13:00:43Z'),
  ('ia-news-day', 'https://deepmind.google/blog/introducing-gemini-38-live-with-live-avatar', 'Introducing Gemini 3.8 Live with Live Avatar', '2026-09-25T13:00:40Z'),
  ('ia-news-day', 'https://openai.com/index/invideo-builds-with-gpt-6-astra', 'How invideo improves color grading 3x with GPT‑6 Astra', '2026-09-25T13:00:40Z')
on conflict (newsletter_id, url) do nothing;
