create table if not exists public.app_slack_channels (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  channel_id text not null,
  channel_name text not null,
  is_private boolean not null default true,
  created_at timestamptz not null default now(),

  unique(workspace_id, channel_id)
);

alter table public.app_slack_channels enable row level security;

create policy "users_can_view_slack_channels"
  on public.app_slack_channels for select
  using (
    workspace_id in (
      select workspace_id
      from public.workspace_memberships
      where profile_id = auth.uid()
    )
  );

create policy "users_can_insert_slack_channels"
  on public.app_slack_channels for insert
  with check (
    workspace_id in (
      select workspace_id
      from public.workspace_memberships
      where profile_id = auth.uid()
    )
  );
